### ISSUE TITLE
Złożonośc obliczeniowa?

### ISSUE THREAD

**Issue by FilipSerewa** [mikoweb/symfony-tsp-application#1]
Oczywiście to nie jest rozwiązanie optymalne tylko jakieś przybliżenie. Pytanie jaka jest złożoność obliczeniowa tego algorytmu?

**Comment by mikoweb** [comment]
Nietypowa sytuacja. Pierwszy raz historii ktoś skomentował moje repozytorium na GitHubie xD

Jak najbardziej jest to rozwiązanie przybliżone, a do uzyskania jak najlepszych rezultatów przetestowałem 8400 zestawów parametrów. Jednak było to testowane jedynie na kilkunastu miastach i tylko do 150 iteracji, a i tak testowanie tego trwało całą noc.

Należy pamiętać, że ten algorytm nie jest czymś jednolitym, bo składa się z wielu elementów, a złożoność jest zależna od liczby miast, liczby mrówek i liczby iteracji. Mrówki i iteracje wpływają liniowo, natomiast liczba miast kwadratowo. Przy kilkunastu miastach działa to całkiem szybko. Przy kilkudziesięciu jest już znacznie gorzej.

**Comment by FilipSerewa** [comment]
A jakoś znalazłem przypadkiem i mnie zaciekawiło. Pomyślałem nawet, że może ktoś przypadkiem rozwiązał problem NP trudny ;)
Dzięki za info ;)
